check_krb5_kinit.pl

Make script compatible with Centos7.  Centos7 uses 4-digit years, eg:
04/26/2015 18:56:33  04/27/2015 18:56:33  krbtgt/MY.DOMAIN.COM@MY.DOMAIN.COM

Support krb monitoring on centos7

---

check_cassandra_balance.pl
check_hbase_regionservers_jsp.pl

Hello,
I had this issue after deploying your script on my server. It seems that newer Cassandra report this value as a %, not as a float.
I'm not a PERL expert at all so you may want to do something else but this line fixed the issue for me.
Best regards, Adam.

Cassandra 3.4 report value with percent sign / HBase JSP new format

---

check_yum.py

If you run 'yum check-update' on RedHat as non root user you get this
message, sadly with a returncode of 0:
*Note* Red Hat Network repositories are not listed below. You must run
this command as root to access RHN repositories.
The current output parsing interpreted this as:
YUM OK: 0 Security Updates Available
which is wrong.

check_yum.py: check if we must run as root

---

check_cassandra_netstats.pl

Fails to run when Dropped column has `n/a`
```
$ /etc/sensu/plugins/harisekhon/check_cassandra_netstats.pl -H 127.0.0.1 -P 7199 -u cassandra -p cassandra
UNKNOWN: unrecognized output 'Responses                       n/a         3        3545563       n/a'
```
Actual netstats output
```
$ nodetool netstats
Mode: NORMAL
Not sending any streams.
Read Repair Statistics:
Attempted: 587
Mismatch (Blocking): 0
Mismatch (Background): 0
Pool Name                    Active   Pending      Completed   Dropped
Commands                        n/a         3          72352         0
Responses                       n/a         3        3545912       n/a
```

Fix cassandra netstats check regex

---

check_whois.pl

.biz uses the following email format.
Administrative Contact Email: dns-admin@google.com
Technical Contact Email: dns-admin@google.com

#143 Allow for .biz email format 

---

check_impala_metrics.pl

Cloudera Impala since CDH 5.4 supports only /jsonmetrics?json handler otherwise it returns "Could not open template: /usr/lib/impala//www//legacy-metrics.tmpl": https://community.cloudera.com/t5/Interactive-Short-cycle-SQL/Could-not-open-template-usr-lib-impala-www-legacy-metrics-tmpl/td-p/26815

Support Impala CDH > 5.4

---

check_elasticsearch.pl
check_elasticsearch_cluster_disk_balance.pl
check_elasticsearch_cluster_shard_balance.pl
check_elasticsearch_cluster_shards.pl
check_elasticsearch_cluster_stats.pl
check_elasticsearch_cluster_status.pl
check_elasticsearch_cluster_status_nodes_shards.pl
check_elasticsearch_data_nodes.pl
check_elasticsearch_doc_count.pl
check_elasticsearch_fielddata.pl
check_elasticsearch_index_age.pl
check_elasticsearch_index_exists.pl
check_elasticsearch_index_replicas.pl
check_elasticsearch_index_settings.pl
check_elasticsearch_index_shards.pl
check_elasticsearch_index_stats.pl
check_elasticsearch_master_node.pl
check_elasticsearch_node_disk_percent.pl
check_elasticsearch_node_shards.pl
check_elasticsearch_node_stats.pl
check_elasticsearch_nodes.pl
check_elasticsearch_pending_tasks.pl
check_elasticsearch_shards_state_detail.pl

For monitoring secured ElasticSearch clusters using Elastic X-Pack or
SearchGuard security
Depends on:
https://github.com/ted3/lib/commit/8feab91751167f188a24764e073c7318e83b8f97
I tested these with ElasticSearch 5.5.1 with SearchGuard TLS and authentication as well as an unsecured cluster to confirm existing functionality is unchanged

adding support for SSL encryption and username/password authentication

---

older/nsca_wrapper.sh

If plugin output contains asterisk in its body, it would be expanded in the echo command. E.g. output like:
* elasticsearch is running
would return list of files in the working directory before the "elasticsearch is running" text.

Added quotes around $output variable (handle asterisk in output)

---

check_yum.py

This option can be used to look for updates for packages that
are pinned via versionlock.
Actually, the option --disableplugin for yum takes a comma
separated list itself, but it works with multiple instances of
the option as well.

Add option --disableplugin

---

check_linux_interface.pl

Sometimes, ethtool returns anything but link.
For example, with libvirt/kvm virtio interfaces.
```.bash
Settings for eth0:
Link detected: yes
```
So, in my opinion,  this script doesn't have to fail if speed or duplex aren't in ethtool output except if explicitly asks for expected values.
Thank you very much.

[check_linux_interfaces.pl] Don't always warn about speed or duplex

---

setup/cpan-requirements-packaged.txt

Fix for error connecting on https:
Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)

FIx for https

---

check_puppet.rb

Hi Hari,
Please find attached a patch inspired from: https://github.com/petems/cucumber-puppet/commit/dd66ac1d4dd5a774ca17d639ef4f23662e5c2771
Fixing the use of an obsolete Puppet method "parse_config"
Regards,

Workaround obsolete Puppet parse_config method

---

check_mesos_metrics.pl

Hello Hari,
I think it might be related to newer Mesos releases but master metrics JSONs now include framework related metrics.
It ended up being an absolutely huge amount of data as we are using dynamic spawn frameworks and they stays in the metrics page.
Here is an example showing what happened without the new option:
```
root@centreon:~# /usr/lib/nagios/plugins/check_mesos_metrics.pl -H mesos.master -P 5050 -f | wc -c
700927
root@centreon:~# /usr/lib/nagios/plugins/check_mesos_metrics.pl -H mesos.master -P 5050 | wc -c
11525
```
Thanks in advance,
Regards, Adam.

mesos_metrics: ignore framework related metrics by default

---

check_puppet.rb

This PR provides a fix for the `check_puppet.rb` file.
When using the command with wrong arguments, a nice error message is supposed to be printed on the screen. Instead, the command exits with a scary TypeError exception.
./check_puppet.rb --foo
The output should be: `PUPPET UNKNOWN: parsing error: invalid option: --foo`.
```
Traceback (most recent call last):
6: from ./check_puppet.rb:48:in `<main>'
5: from ./check_puppet.rb:67:in `<class:CheckPuppet>'
4: from ./check_puppet.rb:67:in `new'
3: from /usr/lib/ruby/2.5.0/optparse.rb:1062:in `initialize'
2: from ./check_puppet.rb:109:in `block in <class:CheckPuppet>'
1: from ./check_puppet.rb:112:in `rescue in block in <class:CheckPuppet>'
./check_puppet.rb:112:in `+': no implicit conversion of OptionParser::InvalidOption into String …
```

Fix check_puppet.rb: remove TypeError when invalid command

---

check_linux_interface.pl

Hi,
i added a small adjustment for parsing of ifconfig output in RHEL7/ Debian10 Distros.
Regards,
Sven

Adjust ifconfig output parsing for RHEL7 / Debian 10

---

older/check_gentoo_portage.py

After updating this file for python 3, it never worked for me. I found out that you need to stdout.decode() in Python3. Maybe this only occurs since Portage 3.0, I'm not sure.

Fix check_gentoo_portage.py for Python 3 and Portage 3.0

---

check_kafka.py

When running the script with python3 I was getting AsserionError. After some
investigation it came out the problem is with message and key not being
properly represented as bytes. The fix makes the script compatible with both
python2 and python3.
The full error I was hitting:
```
Traceback (most recent call last):
File "/opt/python-harisekhon-utils/harisekhon/nagiosplugin/nagiosplugin.py", line 242, in main
super(NagiosPlugin, self).main()
File "/opt/python-harisekhon-utils/harisekhon/cli.py", line 180, in main
self.run()
File "./check_kafka", line 215, in run
super(CheckKafka, self).run()
File "/opt/python-harisekhon-utils/harisekhon/nagiosplugin/pubsub_nagiosplugin.py", line 126, in run
self.publish()
File "./check_kafka", line 315, in publish
value=self.publish_message
File …
```

Fix check_kafka when running with python3

---

check_aws_s3_file.pl

Uses content-length header from HEAD request to determine remote file size

Adding a size option so that files larger than --size will be considered valid

---

check_yum.py

Allow check_yum.py to work compleltly from the cached metadata. Fixes #341.

---

check_kafka.pl

Current installed version of the Kafka perl module
is 1.08. Two parameters still in use by check_kafka.pl
were removed in v 1.001013 of the Kafka perl module, as
mentioned in the changelog:
https://metacpan.org/changes/release/ASOLOVEY/Kafka-1.08
> 1.001013 Fri Feb  24 2017
>    CHANGES:
>    - Removed support for custom CorrelationID in constructor arguments.
>    ...
>    - Removed deprecated constants $RECEIVE_MAX_ATTEMPTS, $RECEIVE_MAX_RETRIES, $SEND_MAX_RETRIES.
check_kafka.pl is erroring until these two now invalid params
are removed.

Remove invalid Kafka perl parameters

---

older/check_md_raid.py

My mdadm output was:
```
sudo /sbin/mdadm --detail /dev/md127
/dev/md127:
Version : 1.2
Creation Time : Mon Jun 21 07:11:36 2021
Raid Level : raid1
Array Size : 732442432 (698.51 GiB 750.02 GB)
Used Dev Size : 732442432 (698.51 GiB 750.02 GB)
Raid Devices : 2
Total Devices : 2
Persistence : Superblock is persistent
Intent Bitmap : Internal
Update Time : Wed Jul 21 12:38:28 2021
State : clean, degraded, recovering
Active Devices : 1
Working Devices : 2
Failed Devices : 0
Spare Devices : 1
Rebuild Status : 10% complete
Name : <redacted>
UUID : <redacted>
Events : 2249
Number   Major   Minor   RaidDevice State
2       8       17        0      spare rebuilding   /dev/sdb1
1       8       33        1      active sync   /dev/sdc1
```
Prior to this change, output was:
`RAID OK: All arrays OK [1 …

Correctly report rebuilding status

---

older/check_md_raid.py

Reverts HariSekhon/Nagios-Plugins#372
Try and fix https://github.com/HariSekhon/Nagios-Plugins/pull/371#issuecomment-884236445
~Sorry I can't convert this to draft for some reason...~ Found where they've moved it to.
Possible states:
`clean, degraded, recovering` - was rebuilding
`clean` - after rebuilding
`clean, no-errors` - Presumably, from https://github.com/HariSekhon/Nagios-Plugins/blob/cd686831d4d730bc58165339a7547602e6619f87/legacy/check_md_raid.py#L105
`active` - Presumably, from https://github.com/HariSekhon/Nagios-Plugins/blob/803b8de921c5254625f26a7107f82d9ba5279551/legacy/check_md_raid.py#L106

Revert "Revert "Correctly report rebuilding status""
